# Generated by Django 4.1.7 on 2023-08-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user_login",
        ),
    ]
